name: okk

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "https://github.com/LEGENDXOP/LEGEND-BOT"

          replace: "https://gthub.com/Sleepers-Cell/Sleepers-Cell-Userbot"

      - name: Pull All Updates

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'there was a conflict'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: Perry-xD

          commit_user_email: 87893142+Perry-xD@users.noreply.github.com

          commit_author: Perry-xD <87893142+Perry-xD@users.noreply.github.com>

